CPDNPQ-1703 Update Cookies Banner to GDS Font
DFE-Digital/npq-registration pull request #1192
Opened 2024-03-01 11:44 UTC by javier-npq

### Context

Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1703

Font in the description text of the cookies banner is not displaying in the GDS style font.

2024-03-01 11:51 UTC, slawosz approved these changes

2024-03-04 15:36 UTC, peteryates commented on app/views/shared/cookies/_accepted.html.erb
>            <p>You’ve accepted additional cookies. You can <%= govuk_link_to "change your cookie settings", cookies_path %> at any time.</p>
```suggestion
        <div class="govuk-cookie-banner__content">
          <p class="govuk-body">You’ve accepted additional cookies. You can <%= govuk_link_to "change your cookie settings", cookies_path %> at any time.</p>
```

2024-03-04 15:38 UTC, peteryates requested changes
Left a comment on the `govuk-body` class, it should be on the individual paragraphs.

2024-03-05 10:41 UTC, dalcJ approved these changes

2024-03-05 11:45 UTC, peteryates approved these changes
Great, thanks @javier-npq!

2024-03-05 12:36 UTC, merged