Clean up service error tests and translations
DFE-Digital/npq-registration pull request #1535
Opened 2024-07-19 07:08 UTC by ethax-ross

[Jira-3244](https://dfedigital.atlassian.net.mcas.ms/browse/CPDLP-3244)

### Context

Update the API service class specs to use the `have_error` matcher.

Clean up the translations file to make it consistent.

### Changes proposed in this pull request

- Clean up service error tests and translations

2024-07-23 18:03 UTC, cwrw commented
@ethax-ross a few failures I think from the other pr possibly?

2024-07-24 15:04 UTC, leandroalemao requested changes
@ethax-ross that's good! Just a small comment.. Tkss

https://github.com/DFE-Digital/npq-registration/blob/6e12b7638850eaecac082998746eafb35d56f776/spec/services/applications/accept_spec.rb#L210

```
expect(service).to have_error(:application, :cannot_change_from_rejected, "Once rejected an application cannot change state")
```

2024-07-25 08:51 UTC, cwrw approved these changes

2024-07-25 09:15 UTC, leandroalemao approved these changes
Tkss @ethax-ross

2024-07-25 09:30 UTC, merged