[CPDNPQ-2178] admin change trn
DFE-Digital/npq-registration pull request #2063
Opened 2024-12-10 09:40 UTC by alkesh

### Context

Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2178

Allow admin users to change a participant's TRN

### Changes proposed in this pull request

Add ability to change TRN from separation admin participant page

2024-12-10 12:26 UTC, alkesh commented on app/views/npq_separation/admin/users/change_trn/show.html.erb
> +  <div class="govuk-grid-column-full">
I made the width full here, because even at three-quarters, the Participant ID wraps.

2024-12-10 17:57 UTC, jebw requested changes
Looks great, some minor changes but this looks pretty much good to go

2024-12-11 09:19 UTC, alkesh commented on spec/services/participants/change_trn_spec.rb
> +      expect(subject).to validate_presence_of(:trn).with_message(:blank).with_message("can't be blank")
<img width="296" alt="Screenshot 2024-12-11 at 09 18 38" src="https://github.com/user-attachments/assets/9f5ab232-0dc5-4835-8185-9c0d1f83aea0">
the error is attached to the `trn` attribute.

2024-12-11 12:17 UTC, alkesh commented on spec/services/participants/change_trn_spec.rb
> +      expect(subject).to validate_presence_of(:trn).with_message(:blank).with_message("can't be blank")
I see what you mean - when `govuk_error_summary` is used in a view, it doesn't include the attribute names.
I've improved the error messages now.

2024-12-16 11:08 UTC, jebw approved these changes
LGTM - just needs a rebase onto current `main` :raised_hands:

2024-12-18 10:20 UTC, merged