Scoping new admin page feature flags
DFE-Digital/npq-registration pull request #2080
Opened 2024-12-16 16:12 UTC by EmmaFrith

### Context

Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-2180

The existing feature flags section is difficult to use and understand for people who aren't developers. We're rebuilding the features section so that:

- it's in GOV.UK style
- it's in keeping with the rest of the admin console
- features have a description so that people know what they do

We want to do this so that relevant members of the NPQ registration team feel confident turning features on and off when needed.

### Changes proposed in this pull request

We've added a new MVP feature flags section to the legacy admin console. 

This currently sits alongside the existing feature flags section. This is so that we still have all the existing functionality as we build out the new MVP. 

The new section includes:

* an index page showing all the features that are in use and not in use (not in use means that they are in the database, but we haven't set them out as a feature that should be used - see the FEATURE_FLAG_KEYS array for those that should be used)
* a show page for each feature that is in use, where you can change the state of the feature and see how many actors there are for the feature 

###

Things we could do next:

* better error handling, in line with GOV.UK design system, on the form to change the feature flag state
* create tests
* add functionality to delete features that aren't in use
* look at whether we need CRUD functionality on the actors section - i.e. deleting an actor 
* add descriptions to all the feature flags - currently we only have descriptions for some of them
* make descriptions essential when creating a feature flag

2024-12-17 12:26 UTC, jebw requested changes
Hey, this looks really good and is a really solid base to build off - it all works great.

There's a four items I'm keen to address - we can work through these this week

* its super minor but there are linting tools we set your computer with (kinda like grammar checkers for developers)
* permissions checks - this checks for admin rights but would be good to extend this to check for super admins instead
* we could do with filtering the features users are allowed to change to just the ones listed in the FeatureFlags class
* it would be great to add a feature spec to automate checking this works as intended

2024-12-17 13:35 UTC, EmmaFrith commented on app/views/admin/features/index.html.erb
> +    <div class="govuk-grid-column-full">
thank you!

2024-12-17 13:37 UTC, EmmaFrith commented on app/services/feature.rb
> +
thank you!

2024-12-17 13:37 UTC, EmmaFrith commented on app/views/admin/features/show.html.erb
> +<%= render GovukComponent::BackLinkComponent.new(
thanks!

2024-12-17 14:44 UTC, EmmaFrith commented on app/controllers/admin/features_controller.rb
> +      @feature = params[:id]
Oh that's such a good point! I hadn't noticed that you can put anything anything at all into the url and you get a show page for it. So would it be something like this?

    def show
      @feature = params[:id]
      if Feature::FEATURE_FLAG_KEYS.include?(@feature)
        @users = User.with_feature_flag_enabled(@feature)
      else
        redirect_back fallback_location: admin_features_path
      end
    end

2025-01-15 18:11 UTC, jebw requested changes
This looks great, really nearly there :raised_hands: 

The missing piece is the superadmin checks which whilst hiding the link aren't actually preventing the new code from being accessed. I've included an explanation of how to test this and resolve it in the comment.

If you want to manually check you can do it by logging in as `admin@` and then changing the url to `/admin/features`

Quite happy to chat this through on friday if you want :+1:

2025-01-15 18:11 UTC, jebw commented on spec/requests/admin/features_controller_spec.rb
> +  end
This looks really great _but_ your spec is highlighting a weakness in your security checks

On line 9 you're signing in as a regular admin _but_ are able to change the feature_flag as a *regular* admin

So to resolve this I'd do 3 things, in the following order (TDD for the win :wink: )

1) Add another context at the bottom copying the 'when not logged in' one but adding a `before { sign_in_as_admin }` line.

If you run your specs now you should find the new context fails, because the code is actually allowing regular admins to access the new features area

2) Change the security checks on your new features controller - this is actually quite simple, it just needs to inherit from `SuperAdminController` instead of from `AdminController`, ie `class Admin::FeaturesController < SuperAdminController`

If you re-run your specs at this point, you should find the new context block passes (its now denying regular admins) _but_ instead the first context block will start failing because that is also trying to update as a regular admin _but_ now you're checking for a super admin instead of a regular one

3) Finally you can change the `before { sign_in_as_admin }` in the first context block to instead sign in as a super admin (`sign_in_as_super_admin`)

At this point your specs should all start passing and your security is checking for superadmins :lock:

2025-01-17 17:55 UTC, jebw approved these changes
LGTM :rocket: :partying_face:

2025-01-23 16:09 UTC, merged