CPDNPQ-1257 Create NPQ Maths user flow on the service
DFE-Digital/npq-registration pull request #850
Opened 2023-08-02 15:19 UTC by javier-npq

### Context

Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1257

### Changes proposed in this pull request

- Add in option for Maths NPQ course selection page
- 3 new pages added just for the Maths NPQ 
- 2 question pages 
- 1 cannot take this course page 
- 1 different funding outcome message

2023-08-11 10:31 UTC, dalcJ commented
1. Remove 'the' here: 
![Screenshot 2023-08-11 at 11 27 52](https://github.com/DFE-Digital/npq-registration/assets/53426640/46d823d7-27db-4149-af6e-2def57cf990b)

2. link this text to https://www.gov.uk/guidance/join-the-maths-teaching-for-mastery-programme 
![Screenshot 2023-08-11 at 11 27 56](https://github.com/DFE-Digital/npq-registration/assets/53426640/c7de3c00-e3fa-490e-a25b-335f9a1059db)

@javier-npq

2023-08-11 10:33 UTC, dalcJ commented
add 15px margin here: 

![Screenshot 2023-08-11 at 11 32 32](https://github.com/DFE-Digital/npq-registration/assets/53426640/53f6327b-7de4-4093-9b35-c6185e20755f)

@javier-npq

2023-08-11 10:36 UTC, dalcJ commented
Add 2 links. 
'primary maths Teaching for Mastery programme' linked to https://www.gov.uk/guidance/join-the-maths-teaching-for-mastery-programme 

'register for a different NPQ' links back to the /registration/choose-your-npq page 

![Screenshot 2023-08-11 at 11 34 31](https://github.com/DFE-Digital/npq-registration/assets/53426640/5d4f3e46-a0db-4564-aac2-0d9af0230454)

@javier-npq

2023-08-11 10:38 UTC, dalcJ commented
The back link on the 'Funding eligibility' page, after selecting either of these options is going to the choose an NPQ page, it should return to this page. 
 
![Screenshot 2023-08-11 at 11 36 58](https://github.com/DFE-Digital/npq-registration/assets/53426640/e59c288b-d7a0-418e-bcfd-6fcfa4bb3b2e)

@javier-npq

2023-08-11 10:39 UTC, dalcJ commented
The back link on the 'Funding eligibility' page, after selecting 'yes' is going to the choose an NPQ page, it should return to this page.

![Screenshot 2023-08-11 at 11 38 46](https://github.com/DFE-Digital/npq-registration/assets/53426640/3882f3e4-87fe-40e0-bff6-758618d88625)

 @javier-npq

2023-08-11 11:15 UTC, dalcJ commented
The funding eligibility outcomes are not correct for when not eligible/ in review. 

These should work in the same way as the other NPQs. 

- Selecting 'No' to 'Do you work in England' = Not eligible. Should see this message: https://npq-prototype.herokuapp.com/funding/funding-not-available-england 
- Selecting Early years > private nursery as setting = not eligible. Should see this message: https://npq-prototype.herokuapp.com/funding/funding-not-available-setting 
- Selecting 'other' for setting = eligibility to be reviewed. Should see this message: https://npq-prototype.herokuapp.com/funding/edge-case

etc. 

@javier-npq

2023-08-11 11:16 UTC, dalcJ requested changes
See comments

2023-08-14 08:58 UTC, javier-npq commented
> add 15px margin here:
> 
> ![Screenshot 2023-08-11 at 11 32 32](https://user-images.githubusercontent.com/53426640/259984225-53f6327b-7de4-4093-9b35-c6185e20755f.png)
> 
> @javier-npq

@dalcJ That hint and options are displayed through a generic view for all pages so it will disturb other pages if we change the margin for this one. I'm afraid we can't touch this for now. But the rest of the changes have been implemented, thanks for a detailed review!

2023-08-14 15:37 UTC, dalcJ commented
Thanks for making the changes Javier. Just a couple of bits. 

The colour of the links on here are not correct: 

![Screenshot 2023-08-14 at 16 34 56](https://github.com/DFE-Digital/npq-registration/assets/53426640/ba9254c2-25f0-4ea3-b1ce-0e05dd5912ff)

@javier-npq

2023-08-14 15:40 UTC, dalcJ commented
> The funding eligibility outcomes are not correct for when not eligible/ in review.
> 
> These should work in the same way as the other NPQs.
> 
> * Selecting 'No' to 'Do you work in England' = Not eligible. Should see this message: https://npq-prototype.herokuapp.com/funding/funding-not-available-england
> * Selecting Early years > private nursery as setting = not eligible. Should see this message: https://npq-prototype.herokuapp.com/funding/funding-not-available-setting
> * Selecting 'other' for setting = eligibility to be reviewed. Should see this message: https://npq-prototype.herokuapp.com/funding/edge-case
> 
> etc.
> 
> @javier-npq

For this one, it's not working quite right. At the moment if the user is not eligible or eligibility is in review. And then they select Primary mathematics they are shown the eligibility outcome as the next page. 

But it should instead take the user to the additional questions that we've added for primary mathematics. They would just see the correct eligibility different message after completing those questions. Let me know if you want to chat over this on a call, might be easier to go through the flow together. 
@javier-npq

2023-08-14 15:44 UTC, dalcJ commented
> > add 15px margin here:
> > ![Screenshot 2023-08-11 at 11 32 32](https://user-images.githubusercontent.com/53426640/259984225-53f6327b-7de4-4093-9b35-c6185e20755f.png)
> > @javier-npq
> 
> @dalcJ That hint and options are displayed through a generic view for all pages so it will disturb other pages if we change the margin for this one. I'm afraid we can't touch this for now. But the rest of the changes have been implemented, thanks for a detailed review!

@javier-npq can't the class `govuk-!-margin-top-3` be added to the radios just on this page?

2023-08-15 10:33 UTC, EmmaFrith commented on app/views/registration_wizard/possible_funding/_funding_eligible_maths.html.erb
> +  If your provider accepts your application, you'll be eligible for scholarship funding for the <%= localise_sentence_embedded_course_name(course) %>.
```suggestion
  If your provider accepts your application, you’ll be eligible for scholarship funding for the <%= localise_sentence_embedded_course_name(course) %>.
```

2023-08-15 10:35 UTC, EmmaFrith commented on app/views/registration_wizard/maths_cannot_register.html.erb
> +  <p class="govuk-body">Join the <a href="https://www.gov.uk/guidance/join-the-maths-teaching-for-mastery-programme">primary maths Teaching for Mastery programme</a> or go back if you want to <a href
```suggestion
  <p class="govuk-body">Join the <a href="https://www.gov.uk/guidance/join-the-maths-teaching-for-mastery-programme">primary maths Teaching for Mastery programme</a> or go back if you want to <a href="<%= registration_wizard_show_url('choose_your_npq'.dasherize) %>">register for a different NPQ</a>.</p>
```

2023-08-15 14:07 UTC, dalcJ commented
@javier-npq  

Also, the route for non-state funded schools is showing as eligible. This should show as not eligible due to setting: 

![Screenshot 2023-08-15 at 15 07 22](https://github.com/DFE-Digital/npq-registration/assets/53426640/586365c3-d045-40a1-b352-1d5e656dd414)

2023-08-25 13:19 UTC, slawosz commented on app/lib/forms/maths_eligibility_teaching_for_mastery.rb
> +        if !wizard.query_store.teacher_catchment_england? || wizard.query_store.kind_of_nursery_private?
You have here 2 branches with the same outcome but actually I really like it as the branching questions are grouped onto logical chunks.

2023-08-25 13:24 UTC, slawosz commented on spec/features/happy_journeys/js/while_working_at_private_childcare_provider_but_not_a_nursery_spec.rb
> +      if Flipper.enabled?(:maths_npq)
Can't Flipper be enabled by default in tests?

2023-08-25 13:55 UTC, slawosz approved these changes

2023-08-25 14:28 UTC, dalcJ approved these changes

2023-08-25 16:37 UTC, peteryates commented
Regarding the margins, shouldn't we just stick to the ones provided by the design system? Is there a slight issue with our markup that's affecting them - they do look smaller than usual (and the legend is very big)

2023-08-29 15:17 UTC, javier-npq commented
> Regarding the margins, shouldn't we just stick to the ones provided by the design system? Is there a slight issue with our markup that's affecting them - they do look smaller than usual (and the legend is very big)

We are using the styling/css provided by the design system. They are present on selected pages as far as i have seen, will be raising a separate ticket where I can have a look at the root cause of this and fix it.

2023-08-29 15:31 UTC, merged