Use email to find/create user from GAI
DFE-Digital/npq-registration pull request #989
Opened 2023-11-08 16:12 UTC by slawosz

### Context

Ticket: https://dfedigital.atlassian.net/browse/CPDNPQ-1470

### Changes proposed in this pull request

In some instances, when the user was registered before, it was impossible to create account because of duplicated email error. 
This PR uses only email to reconcile accounts and is overwriting old account attributes with data from GAI, which is fine as currently GAI service is sole provider of user identity.

2023-11-08 16:28 UTC, javier-npq approved these changes

2023-11-09 10:31 UTC, pmanrubia requested changes

2023-11-09 10:31 UTC, pmanrubia commented on app/models/user.rb
> +    user_from_provider_data = find_or_initialize_by(email: provider_data.info.email)
@slawosz if we don't find the user by the `uid`, if the user changes the email on GAI, then we won't be able to find it.

2023-11-09 11:08 UTC, pmanrubia commented on app/models/user.rb
> +    user_from_provider_data = find_or_initialize_by(email: provider_data.info.email)
I wasn't probably very clear :)

When a user is authenticated in GAI, on NPQ we should only care about the UID from that user in GAI and update all the other information. This information should then be also passed to ECF (if changes)

2023-11-09 13:04 UTC, pmanrubia approved these changes

2023-11-09 14:40 UTC, merged